### ISSUE TITLE
First time loading errors

### ISSUE THREAD

**Issue by ArrowVulcan** [ArrowVulcan/MS2-Skill-Calculator#16]
When I load the page for the first time or from a clean cache this shows up. https://i.imgur.com/lZC5NDD.jpg

**Comment by ChungHoward** [comment]
Strange. I don't have that issue.

https://i.imgur.com/7HbxbO6.png

It appears you were unable to get the jquery.min.js file off the web. Try saving that js file to your /js folder and load from that instead.
