### ISSUE TITLE
Heavy Gunner Electric Blast skill description cannot fit in one FHD display

### ISSUE THREAD

**Issue by MakiseKurisu** [ArrowVulcan/MS2-Skill-Calculator#36]
There is always part of description that are out of screen when using mouse pointer as origin. Maybe limit the upper and lower bound of the description box?

**Comment by ChungHoward** [comment]
Hi,

Thanks for the report. To aid us in resolving this issue, please send us
your screen resolution and the browser you are using.

Thanks!

**Comment by ArrowVulcan** [comment]
I've made some changes to hopefully fix this. Tell me if you still have issues with it going out of screen.
