### ISSUE TITLE
google

### ISSUE THREAD

**Issue by p-groarke** [ArrowVulcan/MS2-Skill-Calculator#37]
You should add your website to google, its quite good.

**Comment by ArrowVulcan** [comment]
What do you mean with "add to google" ?

**Comment by p-groarke** [comment]
I wasn't able to find your website on google. Did you use webmaster tools (or the new search console) to add your website to google index? If so, maybe its worth adding more meta tags or something. Google isn't liking the site ;) You can close this issue if you want.
